[package]
name = "auction-io"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gmeta.workspace = true
gstd.workspace = true
primitive-types.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
nft-io.workspace = true
